# Generated by Django 3.2.4 on 2021-10-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='problems',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
