# Generated by Django 3.2.4 on 2021-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_course_complete',
            field=models.BooleanField(default=False),
        ),
    ]
