# Generated by Django 3.2.4 on 2021-11-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_is_course_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_course_complete',
            new_name='is_course_completed',
        ),
        migrations.AddField(
            model_name='account',
            name='is_course_started',
            field=models.BooleanField(default=False),
        ),
    ]
