# Generated by Django 3.2.4 on 2021-11-05 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211105_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='course_end_datetime',
            field=models.DateTimeField(default=datetime.datetime(1969, 12, 31, 21, 30, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='account',
            name='course_start_datetime',
            field=models.DateTimeField(default=datetime.datetime(1969, 12, 31, 21, 30, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='account',
            name='solved_problems',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
