# Generated by Django 3.2.4 on 2021-11-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211105_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='unsolved_problems',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
